# Generated by Django 4.2.7 on 2024-01-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='mobilenumber',
        ),
    ]
